/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LiveClassesRouteImport } from './routes/live-classes'
import { Route as MockTestsRouteImport } from './routes/mock-tests'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PyqsRouteImport } from './routes/pyqs'
import { Route as QuestionBankRouteImport } from './routes/question-bank'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as RecordedClassesIndexRouteImport } from './routes/recorded-classes.index'
import { Route as RecordedClassesLectureIdRouteImport } from './routes/recorded-classes.$lectureId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveClassesRoute = LiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestsRoute = MockTestsRouteImport.update({
  id: '/mock-tests',
  path: '/mock-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PyqsRoute = PyqsRouteImport.update({
  id: '/pyqs',
  path: '/pyqs',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankRoute = QuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordedClassesIndexRoute = RecordedClassesIndexRouteImport.update({
  id: '/recorded-classes/',
  path: '/recorded-classes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordedClassesLectureIdRoute =
  RecordedClassesLectureIdRouteImport.update({
    id: '/recorded-classes/$lectureId',
    path: '/recorded-classes/$lectureId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-classes': typeof LiveClassesRoute
  '/mock-tests': typeof MockTestsRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/pyqs': typeof PyqsRoute
  '/question-bank': typeof QuestionBankRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/recorded-classes/$lectureId': typeof RecordedClassesLectureIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/recorded-classes/': typeof RecordedClassesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-classes': typeof LiveClassesRoute
  '/mock-tests': typeof MockTestsRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/pyqs': typeof PyqsRoute
  '/question-bank': typeof QuestionBankRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/recorded-classes/$lectureId': typeof RecordedClassesLectureIdRoute
  '/courses': typeof CoursesIndexRoute
  '/recorded-classes': typeof RecordedClassesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live-classes': typeof LiveClassesRoute
  '/mock-tests': typeof MockTestsRoute
  '/onboarding': typeof OnboardingRoute
  '/progress': typeof ProgressRoute
  '/pyqs': typeof PyqsRoute
  '/question-bank': typeof QuestionBankRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/recorded-classes/$lectureId': typeof RecordedClassesLectureIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/recorded-classes/': typeof RecordedClassesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/live-classes'
    | '/mock-tests'
    | '/onboarding'
    | '/progress'
    | '/pyqs'
    | '/question-bank'
    | '/courses/$courseId'
    | '/recorded-classes/$lectureId'
    | '/courses/'
    | '/recorded-classes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/live-classes'
    | '/mock-tests'
    | '/onboarding'
    | '/progress'
    | '/pyqs'
    | '/question-bank'
    | '/courses/$courseId'
    | '/recorded-classes/$lectureId'
    | '/courses'
    | '/recorded-classes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/leaderboard'
    | '/live-classes'
    | '/mock-tests'
    | '/onboarding'
    | '/progress'
    | '/pyqs'
    | '/question-bank'
    | '/courses/$courseId'
    | '/recorded-classes/$lectureId'
    | '/courses/'
    | '/recorded-classes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveClassesRoute: typeof LiveClassesRoute
  MockTestsRoute: typeof MockTestsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProgressRoute: typeof ProgressRoute
  PyqsRoute: typeof PyqsRoute
  QuestionBankRoute: typeof QuestionBankRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  RecordedClassesLectureIdRoute: typeof RecordedClassesLectureIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  RecordedClassesIndexRoute: typeof RecordedClassesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-classes': {
      id: '/live-classes'
      path: '/live-classes'
      fullPath: '/live-classes'
      preLoaderRoute: typeof LiveClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests': {
      id: '/mock-tests'
      path: '/mock-tests'
      fullPath: '/mock-tests'
      preLoaderRoute: typeof MockTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyqs': {
      id: '/pyqs'
      path: '/pyqs'
      fullPath: '/pyqs'
      preLoaderRoute: typeof PyqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank': {
      id: '/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorded-classes/': {
      id: '/recorded-classes/'
      path: '/recorded-classes'
      fullPath: '/recorded-classes/'
      preLoaderRoute: typeof RecordedClassesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorded-classes/$lectureId': {
      id: '/recorded-classes/$lectureId'
      path: '/recorded-classes/$lectureId'
      fullPath: '/recorded-classes/$lectureId'
      preLoaderRoute: typeof RecordedClassesLectureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveClassesRoute: LiveClassesRoute,
  MockTestsRoute: MockTestsRoute,
  OnboardingRoute: OnboardingRoute,
  ProgressRoute: ProgressRoute,
  PyqsRoute: PyqsRoute,
  QuestionBankRoute: QuestionBankRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  RecordedClassesLectureIdRoute: RecordedClassesLectureIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  RecordedClassesIndexRoute: RecordedClassesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
